import type { Course } from '../types/course.types';
import type { Question } from '../types/assessment.types';
import type { Stream } from '../types/user.types';

// Course Database
export const COURSES: Record<Stream, Course[]> = {
  Science: [
    {
      id: 'medicine',
      name: 'Medicine and Surgery',
      stream: 'Science',
      description: 'Study human health, diagnose and treat illnesses, and save lives as a medical doctor.',
      traits: ['analytical', 'compassionate', 'detail-oriented', 'problem-solver'],
      jambSubjects: ['Biology', 'Chemistry', 'Physics', 'English'],
      careerPaths: ['Doctor', 'Surgeon', 'Medical Researcher', 'Consultant'],
      icon: 'heart-pulse',
    },
    {
      id: 'computer-science',
      name: 'Computer Science',
      stream: 'Science',
      description: 'Learn programming, software development, and cutting-edge technology to build the future.',
      traits: ['logical', 'creative', 'tech-savvy', 'innovative'],
      jambSubjects: ['Mathematics', 'Physics', 'Chemistry/Biology', 'English'],
      careerPaths: ['Software Developer', 'Data Scientist', 'AI Engineer', 'Cybersecurity Expert'],
      icon: 'laptop-code',
    },
    {
      id: 'engineering',
      name: 'Engineering (Various)',
      stream: 'Science',
      description: 'Design, build, and innovate solutions to real-world problems in various engineering fields.',
      traits: ['innovative', 'practical', 'mathematical', 'systematic'],
      jambSubjects: ['Mathematics', 'Physics', 'Chemistry', 'English'],
      careerPaths: ['Civil Engineer', 'Mechanical Engineer', 'Electrical Engineer', 'Chemical Engineer'],
      icon: 'cog',
    },
    {
      id: 'pharmacy',
      name: 'Pharmacy',
      stream: 'Science',
      description: 'Study medications, their effects, and how to dispense them safely to improve public health.',
      traits: ['meticulous', 'scientific', 'caring', 'communicative'],
      jambSubjects: ['Biology', 'Chemistry', 'Physics', 'English'],
      careerPaths: ['Pharmacist', 'Clinical Pharmacist', 'Pharmaceutical Researcher', 'Drug Inspector'],
      icon: 'pill',
    },
    {
      id: 'architecture',
      name: 'Architecture',
      stream: 'Science',
      description: 'Design buildings and spaces that blend aesthetics with functionality and sustainability.',
      traits: ['creative', 'visual', 'technical', 'detail-oriented'],
      jambSubjects: ['Mathematics', 'Physics', 'Chemistry/Fine Art', 'English'],
      careerPaths: ['Architect', 'Urban Planner', 'Interior Designer', 'Construction Manager'],
      icon: 'building',
    },
    {
      id: 'nursing',
      name: 'Nursing Science',
      stream: 'Science',
      description: 'Provide direct patient care, support medical teams, and promote health and wellness.',
      traits: ['compassionate', 'patient', 'organized', 'communicative'],
      jambSubjects: ['Biology', 'Chemistry', 'Physics', 'English'],
      careerPaths: ['Registered Nurse', 'Nurse Practitioner', 'Clinical Nurse Specialist', 'Nurse Educator'],
      icon: 'stethoscope',
    },
  ],
  Arts: [
    {
      id: 'law',
      name: 'Law',
      stream: 'Arts',
      description: 'Study legal systems, advocate for justice, and represent clients in various legal matters.',
      traits: ['analytical', 'argumentative', 'ethical', 'articulate'],
      jambSubjects: ['Literature in English', 'Government/History', 'CRK/IRS/Economics', 'English'],
      careerPaths: ['Lawyer', 'Barrister', 'Solicitor', 'Legal Adviser', 'Judge'],
      icon: 'scale',
    },
    {
      id: 'mass-communication',
      name: 'Mass Communication',
      stream: 'Arts',
      description: 'Master storytelling, journalism, broadcasting, and digital media to inform and entertain.',
      traits: ['creative', 'communicative', 'curious', 'outgoing'],
      jambSubjects: ['Literature in English', 'Government/History', 'CRK/Economics', 'English'],
      careerPaths: ['Journalist', 'TV Presenter', 'Public Relations Officer', 'Content Creator'],
      icon: 'radio',
    },
    {
      id: 'english',
      name: 'English and Literary Studies',
      stream: 'Arts',
      description: 'Explore literature, develop critical thinking, and master written and verbal communication.',
      traits: ['literary', 'analytical', 'expressive', 'thoughtful'],
      jambSubjects: ['Literature in English', 'Government/History', 'CRK/French', 'English'],
      careerPaths: ['Writer', 'Editor', 'Teacher', 'Content Strategist', 'Publisher'],
      icon: 'book-open',
    },
    {
      id: 'psychology',
      name: 'Psychology',
      stream: 'Arts',
      description: 'Study the human mind and behaviour to help people overcome challenges and thrive.',
      traits: ['empathetic', 'observant', 'patient', 'analytical'],
      jambSubjects: ['Government/History', 'Biology/Economics', 'CRK/Geography', 'English'],
      careerPaths: ['Psychologist', 'Counsellor', 'HR Specialist', 'Researcher'],
      icon: 'brain',
    },
    {
      id: 'political-science',
      name: 'Political Science',
      stream: 'Arts',
      description: 'Understand governance, political systems, and international relations to shape policy.',
      traits: ['strategic', 'persuasive', 'informed', 'leadership'],
      jambSubjects: ['Government', 'History/Economics', 'CRK/Geography', 'English'],
      careerPaths: ['Politician', 'Policy Analyst', 'Diplomat', 'Political Consultant'],
      icon: 'landmark',
    },
    {
      id: 'international-relations',
      name: 'International Relations',
      stream: 'Arts',
      description: 'Study global politics, diplomacy, and cross-border issues to work on the world stage.',
      traits: ['diplomatic', 'cultural-awareness', 'analytical', 'multilingual'],
      jambSubjects: ['Government', 'History/Economics', 'Geography/Literature', 'English'],
      careerPaths: ['Diplomat', 'Foreign Service Officer', 'NGO Worker', 'International Consultant'],
      icon: 'globe',
    },
  ],
  Commercial: [
    {
      id: 'accounting',
      name: 'Accounting',
      stream: 'Commercial',
      description: 'Manage financial records, audits, and taxation to ensure business financial health.',
      traits: ['numerical', 'meticulous', 'ethical', 'organized'],
      jambSubjects: ['Mathematics', 'Economics', 'Commerce/Government', 'English'],
      careerPaths: ['Accountant', 'Auditor', 'Tax Consultant', 'Financial Analyst'],
      icon: 'calculator',
    },
    {
      id: 'business-administration',
      name: 'Business Administration',
      stream: 'Commercial',
      description: 'Learn to manage organizations, make strategic decisions, and lead business operations.',
      traits: ['leadership', 'strategic', 'communicative', 'entrepreneurial'],
      jambSubjects: ['Mathematics', 'Economics', 'Commerce/Government', 'English'],
      careerPaths: ['Business Manager', 'Entrepreneur', 'Operations Manager', 'Consultant'],
      icon: 'briefcase',
    },
    {
      id: 'economics',
      name: 'Economics',
      stream: 'Commercial',
      description: 'Analyse markets, financial systems, and economic policies to solve societal challenges.',
      traits: ['analytical', 'data-driven', 'critical-thinker', 'informed'],
      jambSubjects: ['Mathematics', 'Economics', 'Commerce/Government', 'English'],
      careerPaths: ['Economist', 'Financial Analyst', 'Policy Adviser', 'Investment Banker'],
      icon: 'trending-up',
    },
    {
      id: 'banking-finance',
      name: 'Banking and Finance',
      stream: 'Commercial',
      description: 'Master financial management, investment strategies, and banking operations.',
      traits: ['numerical', 'risk-taker', 'strategic', 'detail-oriented'],
      jambSubjects: ['Mathematics', 'Economics', 'Commerce/Accounting', 'English'],
      careerPaths: ['Investment Banker', 'Financial Planner', 'Risk Manager', 'Portfolio Manager'],
      icon: 'dollar-sign',
    },
    {
      id: 'marketing',
      name: 'Marketing',
      stream: 'Commercial',
      description: 'Create compelling campaigns, understand consumer behaviour, and drive business growth.',
      traits: ['creative', 'persuasive', 'outgoing', 'innovative'],
      jambSubjects: ['Mathematics', 'Economics', 'Commerce/Government', 'English'],
      careerPaths: ['Marketing Manager', 'Brand Strategist', 'Digital Marketer', 'Sales Manager'],
      icon: 'megaphone',
    },
    {
      id: 'insurance',
      name: 'Insurance',
      stream: 'Commercial',
      description: 'Study risk management and provide financial protection against uncertainties.',
      traits: ['analytical', 'communicative', 'trustworthy', 'problem-solver'],
      jambSubjects: ['Mathematics', 'Economics', 'Commerce/Accounting', 'English'],
      careerPaths: ['Insurance Broker', 'Underwriter', 'Claims Adjuster', 'Risk Analyst'],
      icon: 'shield-check',
    },
  ],
};

// Assessment Questions
export const QUESTIONS: Record<Stream, Question[]> = {
  Science: [
    {
      id: 'sci-q1',
      text: 'How do you feel about working with numbers and solving mathematical problems?',
      type: 'scale',
      stream: 'Science',
      category: 'aptitude',
      options: [
        { id: 'a', label: '1', text: 'I strongly dislike it', value: 1, traits: [] },
        { id: 'b', label: '2', text: 'I don\'t enjoy it much', value: 2, traits: [] },
        { id: 'c', label: '3', text: 'I\'m neutral', value: 3, traits: ['pharmacy', 'nursing'] },
        { id: 'd', label: '4', text: 'I enjoy it', value: 4, traits: ['engineering', 'computer-science', 'architecture'] },
        { id: 'e', label: '5', text: 'I love it', value: 5, traits: ['engineering', 'computer-science'] },
      ],
    },
    {
      id: 'sci-q2',
      text: 'Would you rather work with technology and computers or with people directly?',
      type: 'multiple-choice',
      stream: 'Science',
      category: 'interest',
      options: [
        { id: 'a', label: 'A', text: 'Definitely with technology', value: 5, traits: ['computer-science', 'engineering'] },
        { id: 'b', label: 'B', text: 'Mostly with technology', value: 4, traits: ['computer-science', 'architecture'] },
        { id: 'c', label: 'C', text: 'A mix of both', value: 3, traits: ['pharmacy', 'engineering'] },
        { id: 'd', label: 'D', text: 'Mostly with people', value: 2, traits: ['medicine', 'nursing', 'pharmacy'] },
      ],
    },
    {
      id: 'sci-q3',
      text: 'How comfortable are you with the idea of caring for sick or injured people?',
      type: 'scale',
      stream: 'Science',
      category: 'personality',
      options: [
        { id: 'a', label: '1', text: 'Very uncomfortable', value: 1, traits: ['computer-science', 'engineering'] },
        { id: 'b', label: '2', text: 'Somewhat uncomfortable', value: 2, traits: ['architecture'] },
        { id: 'c', label: '3', text: 'Neutral', value: 3, traits: ['pharmacy'] },
        { id: 'd', label: '4', text: 'Comfortable', value: 4, traits: ['nursing', 'pharmacy'] },
        { id: 'e', label: '5', text: 'Very comfortable', value: 5, traits: ['medicine', 'nursing'] },
      ],
    },
    {
      id: 'sci-q4',
      text: 'Do you enjoy understanding how things work and building or fixing things?',
      type: 'multiple-choice',
      stream: 'Science',
      category: 'aptitude',
      options: [
        { id: 'a', label: 'A', text: 'Yes, I love it!', value: 5, traits: ['engineering', 'computer-science'] },
        { id: 'b', label: 'B', text: 'Yes, somewhat', value: 4, traits: ['engineering', 'architecture'] },
        { id: 'c', label: 'C', text: 'It\'s okay', value: 3, traits: ['pharmacy'] },
        { id: 'd', label: 'D', text: 'Not really', value: 2, traits: ['medicine', 'nursing'] },
      ],
    },
    {
      id: 'sci-q5',
      text: 'How interested are you in biology and chemistry?',
      type: 'scale',
      stream: 'Science',
      category: 'subject-preference',
      options: [
        { id: 'a', label: '1', text: 'Not interested', value: 1, traits: ['computer-science', 'engineering'] },
        { id: 'b', label: '2', text: 'Slightly interested', value: 2, traits: ['architecture'] },
        { id: 'c', label: '3', text: 'Moderately interested', value: 3, traits: ['pharmacy'] },
        { id: 'd', label: '4', text: 'Very interested', value: 4, traits: ['pharmacy', 'nursing'] },
        { id: 'e', label: '5', text: 'Extremely interested', value: 5, traits: ['medicine', 'pharmacy'] },
      ],
    },
    {
      id: 'sci-q6',
      text: 'Which of these activities appeals to you most?',
      type: 'multiple-choice',
      stream: 'Science',
      category: 'interest',
      options: [
        { id: 'a', label: 'A', text: 'Writing code and creating apps', value: 5, traits: ['computer-science'] },
        { id: 'b', label: 'B', text: 'Designing buildings and spaces', value: 4, traits: ['architecture'] },
        { id: 'c', label: 'C', text: 'Conducting lab experiments', value: 4, traits: ['pharmacy', 'medicine'] },
        { id: 'd', label: 'D', text: 'Helping patients recover', value: 5, traits: ['medicine', 'nursing'] },
      ],
    },
    {
      id: 'sci-q7',
      text: 'How do you feel about working long hours in high-pressure situations?',
      type: 'scale',
      stream: 'Science',
      category: 'personality',
      options: [
        { id: 'a', label: '1', text: 'I can\'t handle it', value: 1, traits: [] },
        { id: 'b', label: '2', text: 'I prefer to avoid it', value: 2, traits: ['architecture'] },
        { id: 'c', label: '3', text: 'I can manage it occasionally', value: 3, traits: ['pharmacy', 'computer-science'] },
        { id: 'd', label: '4', text: 'I can handle it well', value: 4, traits: ['engineering', 'nursing'] },
        { id: 'e', label: '5', text: 'I thrive under pressure', value: 5, traits: ['medicine', 'engineering'] },
      ],
    },
    {
      id: 'sci-q8',
      text: 'Do you prefer theoretical knowledge or practical, hands-on work?',
      type: 'multiple-choice',
      stream: 'Science',
      category: 'learning-style',
      options: [
        { id: 'a', label: 'A', text: 'Definitely theoretical', value: 5, traits: ['computer-science'] },
        { id: 'b', label: 'B', text: 'Mostly theoretical', value: 4, traits: ['pharmacy'] },
        { id: 'c', label: 'C', text: 'A balance of both', value: 3, traits: ['architecture', 'engineering'] },
        { id: 'd', label: 'D', text: 'Mostly hands-on', value: 2, traits: ['nursing', 'engineering'] },
      ],
    },
    {
      id: 'sci-q9',
      text: 'How detail-oriented are you when working on projects?',
      type: 'scale',
      stream: 'Science',
      category: 'personality',
      options: [
        { id: 'a', label: '1', text: 'Not very detail-oriented', value: 1, traits: [] },
        { id: 'b', label: '2', text: 'Somewhat detail-oriented', value: 2, traits: [] },
        { id: 'c', label: '3', text: 'Moderately detail-oriented', value: 3, traits: ['computer-science'] },
        { id: 'd', label: '4', text: 'Very detail-oriented', value: 4, traits: ['engineering', 'pharmacy'] },
        { id: 'e', label: '5', text: 'Extremely detail-oriented', value: 5, traits: ['medicine', 'architecture', 'pharmacy'] },
      ],
    },
    {
      id: 'sci-q10',
      text: 'How important is creativity in your ideal career?',
      type: 'scale',
      stream: 'Science',
      category: 'values',
      options: [
        { id: 'a', label: '1', text: 'Not important', value: 1, traits: [] },
        { id: 'b', label: '2', text: 'Slightly important', value: 2, traits: ['pharmacy', 'nursing'] },
        { id: 'c', label: '3', text: 'Moderately important', value: 3, traits: ['engineering'] },
        { id: 'd', label: '4', text: 'Very important', value: 4, traits: ['computer-science', 'architecture'] },
        { id: 'e', label: '5', text: 'Extremely important', value: 5, traits: ['architecture', 'computer-science'] },
      ],
    },
    {
      id: 'sci-q11',
      text: 'Would you enjoy researching and discovering new knowledge?',
      type: 'multiple-choice',
      stream: 'Science',
      category: 'interest',
      options: [
        { id: 'a', label: 'A', text: 'Yes, absolutely!', value: 5, traits: ['medicine', 'computer-science', 'pharmacy'] },
        { id: 'b', label: 'B', text: 'Yes, to some extent', value: 4, traits: ['engineering', 'pharmacy'] },
        { id: 'c', label: 'C', text: 'Maybe occasionally', value: 3, traits: ['architecture'] },
        { id: 'd', label: 'D', text: 'No, not really', value: 2, traits: ['nursing'] },
      ],
    },
    {
      id: 'sci-q12',
      text: 'How comfortable are you with public speaking and presenting ideas?',
      type: 'scale',
      stream: 'Science',
      category: 'personality',
      options: [
        { id: 'a', label: '1', text: 'Very uncomfortable', value: 1, traits: [] },
        { id: 'b', label: '2', text: 'Somewhat uncomfortable', value: 2, traits: ['computer-science'] },
        { id: 'c', label: '3', text: 'Neutral', value: 3, traits: ['pharmacy', 'engineering'] },
        { id: 'd', label: '4', text: 'Comfortable', value: 4, traits: ['architecture', 'nursing'] },
        { id: 'e', label: '5', text: 'Very comfortable', value: 5, traits: ['medicine', 'architecture'] },
      ],
    },
    {
      id: 'sci-q13',
      text: 'Do you prefer working independently or as part of a team?',
      type: 'multiple-choice',
      stream: 'Science',
      category: 'work-style',
      options: [
        { id: 'a', label: 'A', text: 'Definitely independently', value: 5, traits: ['computer-science'] },
        { id: 'b', label: 'B', text: 'Mostly independently', value: 4, traits: ['architecture'] },
        { id: 'c', label: 'C', text: 'A mix of both', value: 3, traits: ['engineering', 'pharmacy'] },
        { id: 'd', label: 'D', text: 'Mostly in a team', value: 2, traits: ['medicine', 'nursing'] },
      ],
    },
    {
      id: 'sci-q14',
      text: 'How interested are you in using technology to solve problems?',
      type: 'scale',
      stream: 'Science',
      category: 'interest',
      options: [
        { id: 'a', label: '1', text: 'Not interested', value: 1, traits: [] },
        { id: 'b', label: '2', text: 'Slightly interested', value: 2, traits: ['nursing'] },
        { id: 'c', label: '3', text: 'Moderately interested', value: 3, traits: ['medicine', 'pharmacy'] },
        { id: 'd', label: '4', text: 'Very interested', value: 4, traits: ['engineering', 'architecture'] },
        { id: 'e', label: '5', text: 'Extremely interested', value: 5, traits: ['computer-science', 'engineering'] },
      ],
    },
    {
      id: 'sci-q15',
      text: 'What type of work environment do you prefer?',
      type: 'multiple-choice',
      stream: 'Science',
      category: 'work-style',
      options: [
        { id: 'a', label: 'A', text: 'Office with computers', value: 5, traits: ['computer-science', 'architecture'] },
        { id: 'b', label: 'B', text: 'Laboratory', value: 4, traits: ['pharmacy', 'medicine'] },
        { id: 'c', label: 'C', text: 'Hospital or clinic', value: 4, traits: ['medicine', 'nursing'] },
        { id: 'd', label: 'D', text: 'Field/construction sites', value: 3, traits: ['engineering'] },
      ],
    },
  ],
  Arts: [
    {
      id: 'arts-q1',
      text: 'How comfortable are you with reading and analysing long texts?',
      type: 'scale',
      stream: 'Arts',
      category: 'aptitude',
      options: [
        { id: 'a', label: '1', text: 'Very uncomfortable', value: 1, traits: [] },
        { id: 'b', label: '2', text: 'Somewhat uncomfortable', value: 2, traits: [] },
        { id: 'c', label: '3', text: 'Neutral', value: 3, traits: ['mass-communication', 'psychology'] },
        { id: 'd', label: '4', text: 'Comfortable', value: 4, traits: ['law', 'political-science'] },
        { id: 'e', label: '5', text: 'Very comfortable', value: 5, traits: ['law', 'english', 'international-relations'] },
      ],
    },
    {
      id: 'arts-q2',
      text: 'Do you enjoy debating and arguing your point of view?',
      type: 'multiple-choice',
      stream: 'Arts',
      category: 'personality',
      options: [
        { id: 'a', label: 'A', text: 'Yes, I love it!', value: 5, traits: ['law', 'political-science'] },
        { id: 'b', label: 'B', text: 'Yes, sometimes', value: 4, traits: ['international-relations'] },
        { id: 'c', label: 'C', text: 'It\'s okay', value: 3, traits: ['mass-communication'] },
        { id: 'd', label: 'D', text: 'Not really', value: 2, traits: ['english', 'psychology'] },
      ],
    },
    {
      id: 'arts-q3',
      text: 'How interested are you in current events and news?',
      type: 'scale',
      stream: 'Arts',
      category: 'interest',
      options: [
        { id: 'a', label: '1', text: 'Not interested', value: 1, traits: [] },
        { id: 'b', label: '2', text: 'Slightly interested', value: 2, traits: ['psychology'] },
        { id: 'c', label: '3', text: 'Moderately interested', value: 3, traits: ['english', 'law'] },
        { id: 'd', label: '4', text: 'Very interested', value: 4, traits: ['mass-communication', 'political-science'] },
        { id: 'e', label: '5', text: 'Extremely interested', value: 5, traits: ['mass-communication', 'political-science', 'international-relations'] },
      ],
    },
    {
      id: 'arts-q4',
      text: 'Would you rather work in front of a camera or behind the scenes?',
      type: 'multiple-choice',
      stream: 'Arts',
      category: 'preference',
      options: [
        { id: 'a', label: 'A', text: 'Definitely in front of the camera', value: 5, traits: ['mass-communication'] },
        { id: 'b', label: 'B', text: 'Mostly in front', value: 4, traits: ['law', 'political-science'] },
        { id: 'c', label: 'C', text: 'Behind the scenes', value: 3, traits: ['english', 'psychology'] },
        { id: 'd', label: 'D', text: 'I don\'t mind either', value: 2, traits: ['international-relations'] },
      ],
    },
    {
      id: 'arts-q5',
      text: 'How interested are you in understanding human behaviour and emotions?',
      type: 'scale',
      stream: 'Arts',
      category: 'interest',
      options: [
        { id: 'a', label: '1', text: 'Not interested', value: 1, traits: [] },
        { id: 'b', label: '2', text: 'Slightly interested', value: 2, traits: [] },
        { id: 'c', label: '3', text: 'Moderately interested', value: 3, traits: ['mass-communication', 'law'] },
        { id: 'd', label: '4', text: 'Very interested', value: 4, traits: ['psychology', 'english'] },
        { id: 'e', label: '5', text: 'Extremely interested', value: 5, traits: ['psychology'] },
      ],
    },
    {
      id: 'arts-q6',
      text: 'Which of these activities appeals to you most?',
      type: 'multiple-choice',
      stream: 'Arts',
      category: 'interest',
      options: [
        { id: 'a', label: 'A', text: 'Writing stories or articles', value: 5, traits: ['english', 'mass-communication'] },
        { id: 'b', label: 'B', text: 'Helping people solve problems', value: 4, traits: ['psychology', 'law'] },
        { id: 'c', label: 'C', text: 'Studying world affairs', value: 4, traits: ['international-relations', 'political-science'] },
        { id: 'd', label: 'D', text: 'Creating media content', value: 5, traits: ['mass-communication'] },
      ],
    },
    {
      id: 'arts-q7',
      text: 'How comfortable are you with public speaking?',
      type: 'scale',
      stream: 'Arts',
      category: 'aptitude',
      options: [
        { id: 'a', label: '1', text: 'Very uncomfortable', value: 1, traits: [] },
        { id: 'b', label: '2', text: 'Somewhat uncomfortable', value: 2, traits: ['english', 'psychology'] },
        { id: 'c', label: '3', text: 'Neutral', value: 3, traits: ['international-relations'] },
        { id: 'd', label: '4', text: 'Comfortable', value: 4, traits: ['mass-communication', 'law'] },
        { id: 'e', label: '5', text: 'Very comfortable', value: 5, traits: ['law', 'mass-communication', 'political-science'] },
      ],
    },
    {
      id: 'arts-q8',
      text: 'Do you enjoy creative writing or storytelling?',
      type: 'multiple-choice',
      stream: 'Arts',
      category: 'interest',
      options: [
        { id: 'a', label: 'A', text: 'Yes, I love it!', value: 5, traits: ['english', 'mass-communication'] },
        { id: 'b', label: 'B', text: 'Yes, somewhat', value: 4, traits: ['mass-communication'] },
        { id: 'c', label: 'C', text: 'It\'s okay', value: 3, traits: ['psychology'] },
        { id: 'd', label: 'D', text: 'Not really', value: 2, traits: ['law', 'political-science', 'international-relations'] },
      ],
    },
    {
      id: 'arts-q9',
      text: 'How interested are you in politics and governance?',
      type: 'scale',
      stream: 'Arts',
      category: 'interest',
      options: [
        { id: 'a', label: '1', text: 'Not interested', value: 1, traits: [] },
        { id: 'b', label: '2', text: 'Slightly interested', value: 2, traits: ['english', 'psychology'] },
        { id: 'c', label: '3', text: 'Moderately interested', value: 3, traits: ['law', 'mass-communication'] },
        { id: 'd', label: '4', text: 'Very interested', value: 4, traits: ['political-science', 'international-relations'] },
        { id: 'e', label: '5', text: 'Extremely interested', value: 5, traits: ['political-science', 'international-relations', 'law'] },
      ],
    },
    {
      id: 'arts-q10',
      text: 'Would you prefer to work with individuals one-on-one or with large groups?',
      type: 'multiple-choice',
      stream: 'Arts',
      category: 'work-style',
      options: [
        { id: 'a', label: 'A', text: 'One-on-one', value: 5, traits: ['psychology', 'english'] },
        { id: 'b', label: 'B', text: 'Small groups', value: 4, traits: ['law'] },
        { id: 'c', label: 'C', text: 'Large groups', value: 3, traits: ['mass-communication', 'political-science'] },
        { id: 'd', label: 'D', text: 'Public audiences', value: 2, traits: ['mass-communication', 'political-science'] },
      ],
    },
    {
      id: 'arts-q11',
      text: 'How important is it for you to help people directly?',
      type: 'scale',
      stream: 'Arts',
      category: 'values',
      options: [
        { id: 'a', label: '1', text: 'Not important', value: 1, traits: [] },
        { id: 'b', label: '2', text: 'Slightly important', value: 2, traits: ['english', 'mass-communication'] },
        { id: 'c', label: '3', text: 'Moderately important', value: 3, traits: ['law', 'international-relations'] },
        { id: 'd', label: '4', text: 'Very important', value: 4, traits: ['psychology', 'law'] },
        { id: 'e', label: '5', text: 'Extremely important', value: 5, traits: ['psychology'] },
      ],
    },
    {
      id: 'arts-q12',
      text: 'Do you enjoy learning about different cultures and languages?',
      type: 'multiple-choice',
      stream: 'Arts',
      category: 'interest',
      options: [
        { id: 'a', label: 'A', text: 'Yes, absolutely!', value: 5, traits: ['international-relations', 'english'] },
        { id: 'b', label: 'B', text: 'Yes, somewhat', value: 4, traits: ['mass-communication', 'english'] },
        { id: 'c', label: 'C', text: 'It\'s okay', value: 3, traits: ['psychology', 'political-science'] },
        { id: 'd', label: 'D', text: 'Not really', value: 2, traits: ['law'] },
      ],
    },
    {
      id: 'arts-q13',
      text: 'How do you handle conflicts or disagreements?',
      type: 'scale',
      stream: 'Arts',
      category: 'personality',
      options: [
        { id: 'a', label: '1', text: 'I avoid them', value: 1, traits: [] },
        { id: 'b', label: '2', text: 'I try to compromise', value: 2, traits: ['psychology', 'english'] },
        { id: 'c', label: '3', text: 'I mediate and find solutions', value: 3, traits: ['international-relations'] },
        { id: 'd', label: '4', text: 'I stand my ground', value: 4, traits: ['law', 'political-science'] },
        { id: 'e', label: '5', text: 'I thrive in debates', value: 5, traits: ['law', 'political-science'] },
      ],
    },
    {
      id: 'arts-q14',
      text: 'Are you more interested in the past, present, or future?',
      type: 'multiple-choice',
      stream: 'Arts',
      category: 'interest',
      options: [
        { id: 'a', label: 'A', text: 'The past (history and literature)', value: 5, traits: ['english', 'law'] },
        { id: 'b', label: 'B', text: 'The present (current events)', value: 4, traits: ['mass-communication', 'psychology'] },
        { id: 'c', label: 'C', text: 'The future (planning and policy)', value: 4, traits: ['political-science', 'international-relations'] },
        { id: 'd', label: 'D', text: 'All of them equally', value: 3, traits: ['law', 'international-relations'] },
      ],
    },
    {
      id: 'arts-q15',
      text: 'What type of work environment do you prefer?',
      type: 'multiple-choice',
      stream: 'Arts',
      category: 'work-style',
      options: [
        { id: 'a', label: 'A', text: 'Office or courtroom', value: 5, traits: ['law'] },
        { id: 'b', label: 'B', text: 'Media house or studio', value: 4, traits: ['mass-communication'] },
        { id: 'c', label: 'C', text: 'Counselling center or school', value: 4, traits: ['psychology', 'english'] },
        { id: 'd', label: 'D', text: 'Government or international organizations', value: 5, traits: ['political-science', 'international-relations'] },
      ],
    },
  ],
  Commercial: [
    {
      id: 'com-q1',
      text: 'How comfortable are you with working with numbers and financial data?',
      type: 'scale',
      stream: 'Commercial',
      category: 'aptitude',
      options: [
        { id: 'a', label: '1', text: 'Very uncomfortable', value: 1, traits: [] },
        { id: 'b', label: '2', text: 'Somewhat uncomfortable', value: 2, traits: ['marketing'] },
        { id: 'c', label: '3', text: 'Neutral', value: 3, traits: ['business-administration', 'marketing'] },
        { id: 'd', label: '4', text: 'Comfortable', value: 4, traits: ['economics', 'banking-finance'] },
        { id: 'e', label: '5', text: 'Very comfortable', value: 5, traits: ['accounting', 'banking-finance', 'economics'] },
      ],
    },
    {
      id: 'com-q2',
      text: 'Do you enjoy persuading and influencing people?',
      type: 'multiple-choice',
      stream: 'Commercial',
      category: 'personality',
      options: [
        { id: 'a', label: 'A', text: 'Yes, I love it!', value: 5, traits: ['marketing', 'business-administration'] },
        { id: 'b', label: 'B', text: 'Yes, sometimes', value: 4, traits: ['insurance', 'business-administration'] },
        { id: 'c', label: 'C', text: 'It\'s okay', value: 3, traits: ['economics'] },
        { id: 'd', label: 'D', text: 'Not really', value: 2, traits: ['accounting', 'banking-finance'] },
      ],
    },
    {
      id: 'com-q3',
      text: 'How interested are you in starting your own business?',
      type: 'scale',
      stream: 'Commercial',
      category: 'interest',
      options: [
        { id: 'a', label: '1', text: 'Not interested', value: 1, traits: [] },
        { id: 'b', label: '2', text: 'Slightly interested', value: 2, traits: ['accounting', 'insurance'] },
        { id: 'c', label: '3', text: 'Moderately interested', value: 3, traits: ['economics', 'banking-finance'] },
        { id: 'd', label: '4', text: 'Very interested', value: 4, traits: ['business-administration', 'marketing'] },
        { id: 'e', label: '5', text: 'Extremely interested', value: 5, traits: ['business-administration', 'marketing'] },
      ],
    },
    {
      id: 'com-q4',
      text: 'Would you rather analyse data or interact with customers?',
      type: 'multiple-choice',
      stream: 'Commercial',
      category: 'preference',
      options: [
        { id: 'a', label: 'A', text: 'Definitely analyse data', value: 5, traits: ['accounting', 'economics', 'banking-finance'] },
        { id: 'b', label: 'B', text: 'Mostly analyse data', value: 4, traits: ['economics', 'insurance'] },
        { id: 'c', label: 'C', text: 'A mix of both', value: 3, traits: ['business-administration'] },
        { id: 'd', label: 'D', text: 'Mostly interact with customers', value: 2, traits: ['marketing', 'insurance'] },
      ],
    },
    {
      id: 'com-q5',
      text: 'How detail-oriented are you when handling tasks?',
      type: 'scale',
      stream: 'Commercial',
      category: 'personality',
      options: [
        { id: 'a', label: '1', text: 'Not very detail-oriented', value: 1, traits: [] },
        { id: 'b', label: '2', text: 'Somewhat detail-oriented', value: 2, traits: ['marketing'] },
        { id: 'c', label: '3', text: 'Moderately detail-oriented', value: 3, traits: ['business-administration', 'economics'] },
        { id: 'd', label: '4', text: 'Very detail-oriented', value: 4, traits: ['banking-finance', 'insurance'] },
        { id: 'e', label: '5', text: 'Extremely detail-oriented', value: 5, traits: ['accounting', 'banking-finance'] },
      ],
    },
    {
      id: 'com-q6',
      text: 'Which of these activities appeals to you most?',
      type: 'multiple-choice',
      stream: 'Commercial',
      category: 'interest',
      options: [
        { id: 'a', label: 'A', text: 'Auditing financial records', value: 5, traits: ['accounting'] },
        { id: 'b', label: 'B', text: 'Creating marketing campaigns', value: 5, traits: ['marketing'] },
        { id: 'c', label: 'C', text: 'Analysing market trends', value: 4, traits: ['economics', 'banking-finance'] },
        { id: 'd', label: 'D', text: 'Managing business operations', value: 4, traits: ['business-administration', 'insurance'] },
      ],
    },
    {
      id: 'com-q7',
      text: 'How comfortable are you with taking calculated risks?',
      type: 'scale',
      stream: 'Commercial',
      category: 'personality',
      options: [
        { id: 'a', label: '1', text: 'Very uncomfortable', value: 1, traits: [] },
        { id: 'b', label: '2', text: 'Somewhat uncomfortable', value: 2, traits: ['accounting'] },
        { id: 'c', label: '3', text: 'Neutral', value: 3, traits: ['economics', 'insurance'] },
        { id: 'd', label: '4', text: 'Comfortable', value: 4, traits: ['business-administration', 'marketing'] },
        { id: 'e', label: '5', text: 'Very comfortable', value: 5, traits: ['banking-finance', 'business-administration'] },
      ],
    },
    {
      id: 'com-q8',
      text: 'Do you enjoy working with spreadsheets and financial software?',
      type: 'multiple-choice',
      stream: 'Commercial',
      category: 'aptitude',
      options: [
        { id: 'a', label: 'A', text: 'Yes, I love it!', value: 5, traits: ['accounting', 'banking-finance'] },
        { id: 'b', label: 'B', text: 'Yes, somewhat', value: 4, traits: ['economics', 'insurance'] },
        { id: 'c', label: 'C', text: 'It\'s okay', value: 3, traits: ['business-administration'] },
        { id: 'd', label: 'D', text: 'Not really', value: 2, traits: ['marketing'] },
      ],
    },
    {
      id: 'com-q9',
      text: 'How interested are you in understanding economic policies and trends?',
      type: 'scale',
      stream: 'Commercial',
      category: 'interest',
      options: [
        { id: 'a', label: '1', text: 'Not interested', value: 1, traits: [] },
        { id: 'b', label: '2', text: 'Slightly interested', value: 2, traits: ['marketing'] },
        { id: 'c', label: '3', text: 'Moderately interested', value: 3, traits: ['business-administration', 'accounting'] },
        { id: 'd', label: '4', text: 'Very interested', value: 4, traits: ['banking-finance', 'insurance'] },
        { id: 'e', label: '5', text: 'Extremely interested', value: 5, traits: ['economics', 'banking-finance'] },
      ],
    },
    {
      id: 'com-q10',
      text: 'Would you prefer a structured routine or a dynamic, changing environment?',
      type: 'multiple-choice',
      stream: 'Commercial',
      category: 'work-style',
      options: [
        { id: 'a', label: 'A', text: 'Structured routine', value: 5, traits: ['accounting', 'insurance'] },
        { id: 'b', label: 'B', text: 'Mostly structured', value: 4, traits: ['banking-finance', 'economics'] },
        { id: 'c', label: 'C', text: 'A mix of both', value: 3, traits: ['business-administration'] },
        { id: 'd', label: 'D', text: 'Dynamic and changing', value: 2, traits: ['marketing', 'business-administration'] },
      ],
    },
    {
      id: 'com-q11',
      text: 'How important is creativity in your ideal career?',
      type: 'scale',
      stream: 'Commercial',
      category: 'values',
      options: [
        { id: 'a', label: '1', text: 'Not important', value: 1, traits: [] },
        { id: 'b', label: '2', text: 'Slightly important', value: 2, traits: ['accounting', 'insurance'] },
        { id: 'c', label: '3', text: 'Moderately important', value: 3, traits: ['economics', 'banking-finance'] },
        { id: 'd', label: '4', text: 'Very important', value: 4, traits: ['business-administration', 'marketing'] },
        { id: 'e', label: '5', text: 'Extremely important', value: 5, traits: ['marketing'] },
      ],
    },
    {
      id: 'com-q12',
      text: 'Do you enjoy problem-solving and strategic thinking?',
      type: 'multiple-choice',
      stream: 'Commercial',
      category: 'aptitude',
      options: [
        { id: 'a', label: 'A', text: 'Yes, absolutely!', value: 5, traits: ['business-administration', 'economics', 'banking-finance'] },
        { id: 'b', label: 'B', text: 'Yes, somewhat', value: 4, traits: ['accounting', 'insurance'] },
        { id: 'c', label: 'C', text: 'It\'s okay', value: 3, traits: ['marketing'] },
        { id: 'd', label: 'D', text: 'Not really', value: 2, traits: [] },
      ],
    },
    {
      id: 'com-q13',
      text: 'How comfortable are you with negotiating and closing deals?',
      type: 'scale',
      stream: 'Commercial',
      category: 'aptitude',
      options: [
        { id: 'a', label: '1', text: 'Very uncomfortable', value: 1, traits: [] },
        { id: 'b', label: '2', text: 'Somewhat uncomfortable', value: 2, traits: ['accounting', 'economics'] },
        { id: 'c', label: '3', text: 'Neutral', value: 3, traits: ['banking-finance'] },
        { id: 'd', label: '4', text: 'Comfortable', value: 4, traits: ['business-administration', 'insurance'] },
        { id: 'e', label: '5', text: 'Very comfortable', value: 5, traits: ['marketing', 'insurance', 'business-administration'] },
      ],
    },
    {
      id: 'com-q14',
      text: 'What type of responsibility would you prefer?',
      type: 'multiple-choice',
      stream: 'Commercial',
      category: 'work-style',
      options: [
        { id: 'a', label: 'A', text: 'Ensuring accuracy and compliance', value: 5, traits: ['accounting', 'insurance'] },
        { id: 'b', label: 'B', text: 'Managing people and resources', value: 4, traits: ['business-administration'] },
        { id: 'c', label: 'C', text: 'Driving sales and growth', value: 4, traits: ['marketing'] },
        { id: 'd', label: 'D', text: 'Analysing and forecasting', value: 5, traits: ['economics', 'banking-finance'] },
      ],
    },
    {
      id: 'com-q15',
      text: 'What type of work environment do you prefer?',
      type: 'multiple-choice',
      stream: 'Commercial',
      category: 'work-style',
      options: [
        { id: 'a', label: 'A', text: 'Corporate office', value: 5, traits: ['accounting', 'banking-finance'] },
        { id: 'b', label: 'B', text: 'Client-facing roles', value: 4, traits: ['insurance', 'marketing'] },
        { id: 'c', label: 'C', text: 'Research and analysis centers', value: 4, traits: ['economics'] },
        { id: 'd', label: 'D', text: 'Dynamic startup environment', value: 3, traits: ['business-administration', 'marketing'] },
      ],
    },
  ],
};

// Features for Dashboard
export const FEATURES = [
  {
    id: 'personalized',
    icon: 'target',
    title: 'Personalised Results',
    description: 'Get career recommendations uniquely matched to your personality, interests, and skills through our advanced assessment algorithm.',
  },
  {
    id: 'ai-powered',
    icon: 'trending-up',
    title: 'AI-Powered Guidance',
    description: 'Receive intelligent insights and actionable advice powered by AI to help you make informed decisions about your future career path.',
  },
  {
    id: 'instant',
    icon: 'sparkles',
    title: 'Instant Results',
    description: 'Complete the assessment and get your personalised career recommendations immediately, with no waiting required.',
  },
];

// Stream Information
export const STREAMS = [
  {
    id: 'Science' as Stream,
    name: 'Science',
    icon: 'flask-conical',
    description: 'For students interested in mathematics, physics, chemistry, biology, and technology.',
  },
  {
    id: 'Arts' as Stream,
    name: 'Arts',
    icon: 'book-open',
    description: 'For students passionate about humanities, languages, social sciences, and creative expression.',
  },
  {
    id: 'Commercial' as Stream,
    name: 'Commercial',
    icon: 'trending-up',
    description: 'For students drawn to business, finance, economics, and entrepreneurship.',
  },
];
